name: libphonenumber2
description: This is a Flutter implementation of libphonenumber. It includes only a few features at the moment, and are added when more functionality is desired.
version: 2.0.2
homepage: https://github.com/emostar/flutter-libphonenumber
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.codeheadlabs.libphonenumber
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: LibphonenumberPlugin

